baseURL = 'https://www.macabot.com/'
languageCode = 'en-us'
theme = 'PaperMod'
title = 'macabot.com'

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Michael Cabot"
disableSpecial1stPost = true
